"""Declarative metadata for the built-in Doubao channel."""

from __future__ import annotations

from app.domain.channel import ChannelManifest, ProvisionFlowSpec


def build_manifest(adapter_version: str = "0.2.0") -> ChannelManifest:
    """Return the public manifest without runtime settings or secrets."""

    return ChannelManifest(
        slug="doubao",
        display_name="Doubao",
        adapter_version=adapter_version,
        protocols=("openai", "anthropic", "responses"),
        capabilities=("chat",),  # Only verified capabilities; multimedia planned for P1
        account_flows=(
            ProvisionFlowSpec(
                id="create-profile",
                kind="manual",
                schema={
                    "type": "object",
                    "properties": {
                        "account_id": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 64,
                            "pattern": r"^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$",
                        },
                        "name": {"type": "string", "maxLength": 128},
                        "priority": {"type": "integer"},
                        "enabled": {"type": "boolean"},
                    },
                    # The local profile id is generated by the provisioner;
                    # operators should never have to invent one for QR login.
                    "required": [],
                    "additionalProperties": False,
                },
                supports={"start": True, "cancel": True},
                timeout_seconds=300,
            ),
            ProvisionFlowSpec(
                id="qr-login",
                kind="qr",
                schema={
                    "type": "object",
                    "properties": {
                        "account_id": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 64,
                            "pattern": r"^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$",
                        },
                        "name": {"type": "string", "maxLength": 128},
                        "priority": {"type": "integer"},
                        "enabled": {"type": "boolean", "default": True},
                    },
                    "required": [],
                    "additionalProperties": False,
                },
                supports={"start": True, "poll": True, "complete": True, "cancel": True},
                timeout_seconds=300,
            ),
            ProvisionFlowSpec(
                id="cookie-import",
                kind="token_import",
                schema={
                    "type": "object",
                    "properties": {
                        "cookie": {
                            "type": "string",
                            "format": "textarea",
                            "secret": True,
                            "title": "Cookie",
                            "description": (
                                "从 doubao.com 浏览器开发者工具复制的完整 Cookie "
                                "请求头，必须包含 sessionid。"
                            ),
                        },
                        "accounts": {
                            "type": "array",
                            "title": "批量账号",
                            "description": (
                                "批量导入：每项为 Cookie 字符串，或包含 "
                                "cookie/cookies 的 JSON（兼容会话导出文件）。"
                            ),
                        },
                        "name": {"type": "string", "maxLength": 128, "title": "账号名称"},
                        "priority": {"type": "integer", "title": "优先级"},
                        "enabled": {"type": "boolean", "default": True, "title": "启用"},
                    },
                    # A single import carries either ``cookie`` or ``accounts``;
                    # the provisioner validates that at least one is present.
                    "required": [],
                    # Compatible session exports carry envelope fields such as
                    # params/type/version; unknown fields are ignored.
                    "additionalProperties": True,
                },
                supports={"import": True},
                timeout_seconds=300,
            ),
        ),
        config_schema_version=2,
        config_schema={
            "type": "object",
            "properties": {
                "platform_base": {"type": "string", "format": "uri"},
                "browser": {
                    "type": "object",
                    "properties": {
                        "enabled": {"type": "boolean", "default": False},
                        "executable": {"type": "string"},
                        "headless": {"type": "boolean", "default": True},
                        "login_path": {"type": "string", "default": "/"},
                        "max_contexts": {"type": "integer", "minimum": 1, "default": 4},
                        "max_pages_per_context": {
                            "type": "integer",
                            "minimum": 1,
                            "default": 2,
                        },
                        "operation_timeout_seconds": {
                            "type": "number",
                            "exclusiveMinimum": 0,
                            "default": 30,
                        },
                        "launch_timeout_seconds": {
                            "type": "number",
                            "exclusiveMinimum": 0,
                            "default": 30,
                        },
                        "session_ttl_seconds": {
                            "type": "number",
                            "exclusiveMinimum": 0,
                            "default": 300,
                        },
                    },
                    "additionalProperties": False,
                },
            },
            "additionalProperties": False,
        },
        health_checks=("browser_worker", "credential_store"),
        limits={
            "browser": {
                "max_contexts": 4,
                "max_pages_per_context": 2,
                "restart_on_disconnect": True,
            }
        },
    )


DOUBAO_MANIFEST = build_manifest()
