#!/usr/bin/env python3
"""Verify that All2API builds and starts without the source projects.

The repository intentionally keeps a small, disabled compatibility bridge while
the migration is in progress.  This check therefore validates the target
runtime boundary instead of pretending the bridge files do not exist:

* no source-project paths, imports, or management ports occur in runtime code;
* all checked-in environment templates leave legacy bridge values empty;
* the bridge is disabled by default;
* the removed account-sync endpoint and client hooks are not reintroduced;
* the API can start with a temporary database and answer ``healthz`` on a
  random local port.

Use ``--docker`` in CI or on a machine with Docker to validate the Compose
configuration as well.  A local developer can use the default mode without
changing their existing ``services/api/.env`` or stopping a running instance.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen


ROOT = Path(__file__).resolve().parents[1]
API_DIR = ROOT / "services" / "api"

# These identifiers must never be required by the in-process adapters.  The
# migration-only compatibility modules may still mention "legacy" in prose,
# but the source projects and their management ports must not leak into code.
FORBIDDEN_RUNTIME_TOKENS = (
    r"F:\\token-p",
    "wb2api",
    "doubao2api",
    "chatgpt2api",
    ":7863",
    ":7864",
    ":9090",
    ":8000",
)
RUNTIME_SUFFIXES = {".py", ".pyi", ".toml", ".yaml", ".yml", ".json"}
ENV_TEMPLATE_NAMES = (ROOT / ".env.example", API_DIR / ".env.example")
UPSTREAM_KEYS = re.compile(
    r"^A2A_(?:LEGACY_)?(?:WB|DOUBAO|CHATGPT)_UPSTREAM_BASE\s*=\s*(.*)$",
    re.IGNORECASE,
)
BRIDGE_KEY = re.compile(r"^A2A_LEGACY_BRIDGE_ENABLED\s*=\s*(.*)$", re.IGNORECASE)
REMOVED_ACCOUNT_SYNC_TOKENS = (
    "sync_accounts",
    "syncAccounts",
)


class CheckFailure(RuntimeError):
    """A clean-build assertion failed."""


def _check_runtime_scan() -> None:
    failures: list[str] = []
    runtime_files = [
        path
        for path in (API_DIR / "app").rglob("*")
        if path.is_file()
    ]
    runtime_files.extend(
        path for path in (API_DIR / "Dockerfile", ROOT / "docker-compose.yml") if path.exists()
    )
    for path in runtime_files:
        if not path.is_file() or path.suffix.lower() not in RUNTIME_SUFFIXES:
            if path.name != "Dockerfile":
                continue
        # Avoid treating generated bytecode or editor files as source.
        text = path.read_text(encoding="utf-8", errors="ignore")
        for token in FORBIDDEN_RUNTIME_TOKENS:
            if token.lower() in text.lower():
                failures.append(f"{path.relative_to(ROOT)} contains forbidden token {token!r}")
    if failures:
        raise CheckFailure("Runtime source scan failed:\n- " + "\n- ".join(failures))


def _check_environment_templates() -> None:
    failures: list[str] = []
    for path in ENV_TEMPLATE_NAMES:
        if not path.exists():
            failures.append(f"missing environment template: {path.relative_to(ROOT)}")
            continue
        for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            match = UPSTREAM_KEYS.match(f"{key.strip()}={value.strip()}")
            if match and match.group(1).strip().strip('"\''):
                failures.append(
                    f"{path.relative_to(ROOT)}:{line_number} keeps a legacy upstream value"
                )
            bridge = BRIDGE_KEY.match(f"{key.strip()}={value.strip()}")
            if bridge and bridge.group(1).strip().lower() not in {"false", "0", "no", "off"}:
                failures.append(
                    f"{path.relative_to(ROOT)}:{line_number} must disable the legacy bridge"
                )

    compose = ROOT / "docker-compose.yml"
    if not compose.exists():
        failures.append("docker-compose.yml is missing")
    else:
        compose_text = compose.read_text(encoding="utf-8")
        if "A2A_LEGACY_BRIDGE_ENABLED: ${A2A_LEGACY_BRIDGE_ENABLED:-false}" not in compose_text:
            failures.append("docker-compose.yml must default A2A_LEGACY_BRIDGE_ENABLED to false")
        # Compose defaults use the ``${VAR:-}`` form.  Reject a non-empty
        # default for every legacy upstream base even if the variable is not in
        # either .env template.
        for key in (
            "A2A_LEGACY_WB_UPSTREAM_BASE",
            "A2A_LEGACY_DOUBAO_UPSTREAM_BASE",
            "A2A_LEGACY_CHATGPT_UPSTREAM_BASE",
        ):
            if re.search(rf"{re.escape(key)}:\s*\$\{{{re.escape(key)}:-([^}}]*)}}", compose_text):
                match = re.search(
                    rf"{re.escape(key)}:\s*\$\{{{re.escape(key)}:-([^}}]*)}}", compose_text
                )
                assert match is not None
                if match.group(1).strip():
                    failures.append(f"docker-compose.yml gives {key} a non-empty default")
    if failures:
        raise CheckFailure("Environment boundary check failed:\n- " + "\n- ".join(failures))


def _check_removed_account_sync() -> None:
    """Keep the intentionally removed upstream-account sync feature absent."""

    failures: list[str] = []
    source_roots = (API_DIR / "app", ROOT / "web" / "src")
    suffixes = {".py", ".ts", ".tsx", ".js", ".jsx"}
    for source_root in source_roots:
        if not source_root.exists():
            continue
        for path in source_root.rglob("*"):
            if not path.is_file() or path.suffix.lower() not in suffixes:
                continue
            text = path.read_text(encoding="utf-8", errors="ignore")
            for token in REMOVED_ACCOUNT_SYNC_TOKENS:
                if token in text:
                    failures.append(f"{path.relative_to(ROOT)} contains removed feature {token!r}")
    if failures:
        raise CheckFailure("Removed account-sync feature found:\n- " + "\n- ".join(failures))


def _check_compose_config() -> None:
    docker = shutil.which("docker")
    if not docker:
        raise CheckFailure("--docker was requested, but Docker is not installed")
    result = subprocess.run(
        [docker, "compose", "config", "--quiet"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        env={**os.environ, "A2A_LEGACY_BRIDGE_ENABLED": "false"},
        check=False,
    )
    if result.returncode:
        detail = (result.stderr or result.stdout).strip()
        raise CheckFailure(f"docker compose config failed: {detail}")


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _healthcheck() -> None:
    """Start an isolated API process and check its database-backed healthz."""

    port = _free_port()
    with tempfile.TemporaryDirectory(prefix="all2api-clean-") as temporary:
        temp_dir = Path(temporary)
        env = os.environ.copy()
        env.update(
            {
                "A2A_HOST": "127.0.0.1",
                "A2A_PORT": str(port),
                "A2A_DB_PATH": str(temp_dir / "all2api.db"),
                "A2A_STATE_PATH": str(temp_dir / "state.json"),
                "A2A_SESSION_SECRET": "clean-build-session-secret",
                "A2A_CREDENTIAL_MASTER_KEY": "clean-build-credential-secret",
                "A2A_ADMIN_PASSWORD": "CleanBuild-Admin-Password-1",
                "A2A_ALLOW_WEAK_ADMIN_PASSWORD": "true",
                "A2A_LEGACY_BRIDGE_ENABLED": "false",
                # Override both explicit migration keys and deprecated aliases,
                # even when a developer's local .env file contains old values.
                "A2A_LEGACY_WB_UPSTREAM_BASE": "",
                "A2A_LEGACY_DOUBAO_UPSTREAM_BASE": "",
                "A2A_LEGACY_CHATGPT_UPSTREAM_BASE": "",
                "A2A_WB_UPSTREAM_BASE": "",
                "A2A_DOUBAO_UPSTREAM_BASE": "",
                "A2A_CHATGPT_UPSTREAM_BASE": "",
            }
        )
        command = ["uv", "run", "--no-sync", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", str(port)]
        if not shutil.which(command[0]):
            command = [sys.executable, "-m", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", str(port)]
        process = subprocess.Popen(
            command,
            cwd=API_DIR,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        url = f"http://127.0.0.1:{port}/admin/api/healthz"
        deadline = time.monotonic() + 25
        response: dict[str, object] | None = None
        last_error = "server did not answer"
        try:
            while time.monotonic() < deadline:
                if process.poll() is not None:
                    output = process.stdout.read() if process.stdout else ""
                    raise CheckFailure(
                        f"API exited before healthz ({process.returncode}): {output[-4000:]}"
                    )
                try:
                    with urlopen(url, timeout=1) as result:  # noqa: S310 - local random port
                        if result.status == 200:
                            response = json.loads(result.read().decode("utf-8"))
                            break
                        last_error = f"HTTP {result.status}"
                except (OSError, URLError, ValueError) as exc:
                    last_error = str(exc)
                time.sleep(0.25)
            if response != {"status": "ok", "service": "all2api-api", "database": "ok"}:
                output = process.stdout.read() if process.stdout else ""
                raise CheckFailure(
                    f"API healthz failed ({last_error}); response={response!r}; output={output[-4000:]}"
                )
        finally:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=5)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--docker",
        action="store_true",
        help="also run docker compose config --quiet (requires Docker)",
    )
    parser.add_argument(
        "--skip-health",
        action="store_true",
        help="only scan configuration; do not start a temporary API process",
    )
    args = parser.parse_args()

    checks = [_check_runtime_scan, _check_environment_templates, _check_removed_account_sync]
    if args.docker:
        checks.append(_check_compose_config)
    if not args.skip_health:
        checks.append(_healthcheck)
    try:
        for check in checks:
            check()
            print(f"PASS {check.__name__}")
    except CheckFailure as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1
    print("All2API clean build/run verification passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
